
/* Diese Datei wird in der CONST.PAS eingebunden. */


/* constants file */
CONST
     /* ******************************************************************* */
     /* Sibyl main menu                                                     */
     /* ******************************************************************* */

     /* File Menu */
     SiMenuFile                         = 1;
     SiMenuFileHint                     = 2;
     SiMenuNew                          = 3;
     SiMenuNewHint                      = 4;
     SiMenuNewFile                      = 5;
     SiMenuNewFileHint                  = 6;
     SiMenuOpen                         = 7;
     SiMenuOpenHint                     = 8;
     SiMenuInsert                       = 9;
     SiMenuInsertHint                   = 10;
     SiMenuSave                         = 11;
     SiMenuSaveHint                     = 12;
     SiMenuSaveAs                       = 13;
     SiMenuSaveAsHint                   = 14;
     SiMenuSaveAll                      = 15;
     SiMenuSaveAllHint                  = 16;
     SiMenuPrint                        = 17;
     SiMenuPrintHint                    = 18;
     SiMenuCreateDir                    = 19;
     SiMenuCreateDirHint                = 20;
     SiMenuChangeDir                    = 21;
     SiMenuChangeDirHint                = 22;
     SiMenuExit                         = 23;
     SiMenuExitHint                     = 24;

     /* Edit Menu */
     SiMenuEdit                         = 25;
     SiMenuEditHint                     = 26;
     SiMenuUndo                         = 27;
     SiMenuUndoHint                     = 28;
     SiMenuRedo                         = 29;
     SiMenuRedoHint                     = 30;
     SiMenuCut                          = 31;
     SiMenuCutHint                      = 32;
     SiMenuCopy                         = 33;
     SiMenuCopyHint                     = 34;
     SiMenuPaste                        = 35;
     SiMenuPasteHint                    = 36;
     SiMenuDelete                       = 37;
     SiMenuDeleteHint                   = 38;
     SiMenuSelectAll                    = 39;
     SiMenuSelectAllHint                = 40;
     SiMenuDeselectAll                  = 41;
     SiMenuDeselectAllHint              = 42;
     SiMenuRecordMacro                  = 43;
     SiMenuRecordMacroHint              = 44;
     SiMenuPlayMacro                    = 45;
     SiMenuPlayMacroHint                = 46;
     SiMenuSaveMacro                    = 47;
     SiMenuSaveMacroHint                = 48;
     SiMenuSelectMode                   = 972;
     SiMenuSelectModeHint               = 973;

     /* Search Menu */
     SiMenuSearch                       = 49;
     SiMenuSearchHint                   = 50;
     SiMenuFind                         = 51;
     SiMenuFindHint                     = 52;
     SiMenuReplace                      = 53;
     SiMenuReplaceHint                  = 54;
     SiMenuSearchAgain                  = 55;
     SiMenuSearchAgainHint              = 56;
     SiMenuIncrementalSearch            = 57;
     SiMenuIncrementalSearchHint        = 58;
     SiMenuGotoLine                     = 59;
     SiMenuGotoLineHint                 = 60;
     SiMenuGotoLastError                = 61;
     SiMenuGotoLastErrorHint            = 62;
     SiMenuBookmarks                    = 63;
     SiMenuBookmarksHint                = 64;

     /* View Menu */
     SiMenuView                         = 65;
     SiMenuViewHint                     = 66;
     SiMenuProjectManager               = 67;
     SiMenuProjectManagerHint           = 68;
     SiMenuBrowser                      = 69;
     SiMenuBrowserHint                  = 70;
     SiMenuWindowList                   = 71;
     SiMenuWindowListHint               = 72;
     SiMenuMacroList                    = 73;
     SiMenuMacroListHint                = 74;
     SiMenuClipboardHistory             = 75;
     SiMenuClipboardHistoryHint         = 76;
     SiMenuObjectInspector              = 77;
     SiMenuObjectInspectorHint          = 78;
     SiMenuComponentList                = 79;
     SiMenuComponentListHint            = 80;
     SiMenuAlignmentPalette             = 81;
     SiMenuAlignmentPaletteHint         = 82;
     SiMenuSwitchFormUnit               = 83;
     SiMenuSwitchFormUnitHint           = 84;
     SiMenuNewForm                      = 85;
     SiMenuNewFormHint                  = 86;
     SiMenuImpSibylDelphiForm           = 87;
     SiMenuImpSibylDelphiFormHint       = 88;
     SiMenuSpeedBar                     = 89;
     SiMenuSpeedBarHint                 = 90;
     SiMenuComponentPalette             = 91;
     SiMenuComponentPaletteHint         = 92;
     SiMenuStatusBar                    = 95;
     SiMenuStatusBarHint                = 96;

     /* Component Menu */
     SiMenuComponent                    = 97;
     SiMenuComponentHint                = 98;
     SiMenuComponentNew                 = 99;
     SiMenuComponentNewHint             = 100;
     SiMenuComponentInstall             = 101;
     SiMenuComponentInstallHint         = 102;
     SiMenuComponentRemove              = 103;
     SiMenuComponentRemoveHint          = 104;
     SiMenuOpenLibrary                  = 105;
     SiMenuOpenLibraryHint              = 106;
     SiMenuRebuildLibrary               = 107;
     SiMenuRebuildLibraryHint           = 108;
     SiMenuConfigurePalette             = 109;
     SiMenuConfigurePaletteHint         = 110;
     SiMenuConfigureRepository          = 111;
     SiMenuConfigureRepositoryHint      = 112;
     SiMenuImportTemplateForms          = 113;
     SiMenuImportTemplateFormsHint      = 114;
     SiMenuExportTemplateForms          = 115;
     SiMenuExportTemplateFormsHint      = 116;
     SiMenuAddFormToRepository          = 117;
     SiMenuAddFormToRepositoryHint      = 118;

     /* Debug Menu */
     SiMenuDebug                        = 119;
     SiMenuDebugHint                    = 120;
     SiMenuToggleBreakPoint             = 121;
     SiMenuToggleBreakPointHint         = 122;
     SiMenuClearAllBreakPoints          = 123;
     SiMenuClearAllBreakPointsHint      = 124;
     SiMenuGo                           = 125;
     SiMenuGoHint                       = 126;
     SiMenuGotoCursor                   = 127;
     SiMenuGotoCursorHint               = 128;
     SiMenuStepOver                     = 129;
     SiMenuStepOverHint                 = 130;
     SiMenuTraceInto                    = 131;
     SiMenuTraceIntoHint                = 132;
     SiMenuReturnFromFunction           = 133;
     SiMenuReturnFromFunctionHint       = 134;
     SiMenuProgramReset                 = 135;
     SiMenuProgramResetHint             = 136;
     SiMenuReloadProgram                = 137;
     SiMenuReloadProgramHint            = 138;
     SiMenuEvaluateModify               = 139;
     SiMenuEvaluateModifyHint           = 140;
     SiMenuAddWatch                     = 141;
     SiMenuAddWatchHint                 = 142;
     SiMenuInspect                      = 143;
     SiMenuInspectHint                  = 144;
     SiMenuWatchPoints                  = 145;
     SiMenuWatchPointsHint              = 146;
     SiMenuBreakPoints                  = 147;
     SiMenuBreakPointsHint              = 148;
     SiMenuLocalVariables               = 149;
     SiMenuLocalVariablesHint           = 150;
     SiMenuSourceFiles                  = 151;
     SiMenuSourceFilesHint              = 152;
     SiMenuSymbols                      = 153;
     SiMenuSymbolsHint                  = 154;
     SiMenuCPUWindow                    = 155;
     SiMenuCPUWindowHint                = 156;
     SiMenuWatchWindow                  = 157;
     SiMenuWatchWindowHint              = 158;
     SiMenuStorage                      = 159;
     SiMenuStorageHint                  = 160;

     /* Project Menu */
     SiMenuProject                      = 161;
     SiMenuProjectHint                  = 162;
     SiMenuRun                          = 163;
     SiMenuRunHint                      = 164;
     SiMenuParameters                   = 165;
     SiMenuParametersHint               = 166;
     SiMenuCompile                      = 167;
     SiMenuCompileHint                  = 168;
     SiMenuMake                         = 169;
     SiMenuMakeHint                     = 170;
     SiMenuBuild                        = 171;
     SiMenuBuildHint                    = 172;
     SiMenuBreak                        = 173;
     SiMenuBreakHint                    = 174;
     SiMenuProjectNew                   = 175;
     SiMenuProjectNewHint               = 176;
     SiMenuProjectOpen                  = 177;
     SiMenuProjectOpenHint              = 178;
     SiMenuProjectClose                 = 179;
     SiMenuProjectCloseHint             = 180;
     SiMenuProjectSave                  = 181;
     SiMenuProjectSaveHint              = 182;
     SiMenuProjectSaveAs                = 183;
     SiMenuProjectSaveAsHint            = 184;
     SiMenuProjectSettings              = 185;
     SiMenuProjectSettingsHint          = 186;
     SiMenuCreateLngFile                = 970;
     SiMenuCreateLngFileHint            = 971;

     /* Options Menu */
     SiMenuOptions                      = 187;
     SiMenuOptionsHint                  = 188;
     SiMenuGeneral                      = 189;
     SiMenuGeneralHint                  = 190;
     SiMenuLanguageSettings             = 191;
     SiMenuLanguageSettingsHint         = 192;
     SiMenuTools                        = 193;
     SiMenuToolsHint                    = 194;

     /* Window Menu */
     SiMenuWindow                       = 195;
     SiMenuWindowHint                   = 196;
     SiMenuTile                         = 197;
     SiMenuTileHint                     = 198;
     SiMenuCascade                      = 199;
     SiMenuCascadeHint                  = 200;
     SiMenuCloseAll                     = 201;
     SiMenuCloseAllHint                 = 202;
     SiMenuMaximize                     = 203;
     SiMenuMaximizeHint                 = 204;
     SiMenuNext                         = 205;
     SiMenuNextHint                     = 206;
     SiMenuPrevious                     = 207;
     SiMenuPreviousHint                 = 208;
     SiMenuClose                        = 209;
     SiMenuCloseHint                    = 210;

     /* Help Menu */
     SiMenuHelp                         = 211;
     SiMenuHelpHint                     = 212;
     SiMenuContents                     = 213;
     SiMenuContentsHint                 = 214;
     SiMenuIndex                        = 215;
     SiMenuIndexHint                    = 216;
     SiMenuHelpOnHelp                   = 217;
     SiMenuHelpOnHelpHint               = 218;
     SiMenuKeysHelp                     = 219;
     SiMenuKeysHelpHint                 = 220;
     SiMenuTopicSearch                  = 221;
     SiMenuTopicSearchHint              = 222;
     SiMenuProductInformation           = 225;
     SiMenuProductInformationHint       = 226;

     /* Language identifier */
     SiSibylLanguage                    = 227;
     SiSibylLanguageShort               = 1642;

     /* ******************************************************************* */
     /* About dialog                                                        */
     /* ******************************************************************* */
     SiProductInformation               = 228;
     SiVisualPascalDevelopmentTool      = 229;

     /* ******************************************************************* */
     /* Sliding undo dialog                                                 */
     /* ******************************************************************* */
     SiSlidingUndo                      = 233;
     SiFirst                            = 234;
     SiLast                             = 235;

     /* ******************************************************************* */
     /* BookmarksDialog                                                     */
     /* ******************************************************************* */
     SiBookmarks                        = 236;
     SiAdd                              = 237;
     SiRemove                           = 238;
     SiName                             = 239;
     SiFile                             = 240;
     SiBrowse                           = 241;
     SiLine                             = 242;
     SiCurrentEditorPos                 = 243;
     SiGoto                             = 244;
     SiClose                            = 245;
     SiSelectAFile                      = 246;
     SiSelect                           = 247;
     SiCouldNotLoadFile                 = 248;

     /* ******************************************************************* */
     /* Project Settings Dialog                                             */
     /* ******************************************************************* */
     SiProjectSettings                  = 249;
     SiSavePageAsStandard               = 250;
     SiSavePageAsStandardHint           = 251;

     /* Compiler Page */
     SiCompiler                         = 252;
     SiCompilerHint                     = 253;
     SiPlatform                         = 254;
     SiPlatformHint                     = 255;
     SiCodeGeneration                   = 256;
     SiGenerateAssemblerSource          = 257;
     SiGenerateAssemblerSourceHint      = 258;
     SiInlineStringFunctions            = 259;
     SiInlineStringFunctionsHint        = 260;
     SiSyntaxOptions                    = 261;
     SiStrictVarStrings                 = 262;
     SiStrictVarStringsHint             = 263;
     SiCompleteBooleanEval              = 264;
     SiCompleteBooleanEvalHint          = 265;
     SiOptimizations                    = 266;
     SiOptimizationsHint                = 267;
     SiCommonSubexpressions             = 268;
     SiCommonSubexpressionsHint         = 269;
     SiPeepholeOptimization             = 270;
     SiPeepholeOptimizationHint         = 271;
     SiRunTimeErrors                    = 272;
     SiIOChecking                       = 273;
     SiIOCheckingHint                   = 274;
     SiOverflowChecking                 = 275;
     SiOverflowCheckingHint             = 276;
     SiStackChecking                    = 277;
     SiStackCheckingHint                = 278;
     SiRangeChecking                    = 279;
     SiRangeCheckingHint                = 280;
     SiCondDefines                      = 281;
     SiEnterCondDefsHere                = 282;

     /* Warnings Page */
     SiWarning                          = 283;
     SiWarningsHint                     = 284;
     SiCompilerWarnings                 = 285;
     SiCompilerWarningsHint             = 286;
     SiPossibleUseBeforeDef             = 287;
     SiPossibleUseBeforeDefHint         = 288;
     SiInheritedPropertyRedef           = 289;
     SiInheritedPropertyRedefHint       = 290;
     SiInheritedVarRedef                = 291;
     SiInheritedVarRedefHint            = 292;
     SiVirtualMethRedef                 = 293;
     SiVirtualMethRedefHint             = 294;
     SiIdentDeclaredNeverUsed           = 295;
     SiIdentDeclaredNeverUsedHint       = 296;
     SiParamDeclaredNeverUsed           = 297;
     SiParamDeclaredNeverUsedHint       = 298;
     SiFunctionShouldRet                = 299;
     SiFunctionShouldRetHint            = 300;
     SiSelectWarnings                   = 301;
     SiSelectWarningsHint               = 302;
     SiSelected                         = 303;
     SiSelectedHint                     = 304;
     SiAll                              = 305;
     SiAllHint                          = 306;
     SiNone                             = 307;
     SiNoneHint                         = 308;
     SiSetupWarnError                   = 309;
     SiStopAfter                        = 310;
     SiStopAfterHint                    = 311;
     SiWarnCountHint                    = 312;
     SiAfterWarnings                    = 313;
     SiStopAfterHint2                   = 314;
     SiErrCountHint                     = 315;
     SiAfterErrors                      = 316;

     /* Linker Page */
     SiLinker                           = 317;
     SiLinkerHint                       = 318;
     SiLinkerTarget                     = 319;
     SiGUI                              = 320;
     SiGUIHint                          = 321;
     SiTextModeFull                     = 322;
     SiTextModeFullHint                 = 323;
     SiTextModeWindow                   = 324;
     SiTextModeWindowHint               = 325;
     SiMemorySizes                      = 326;
     SiMemorySizesHint                  = 327;
     SiHeap                             = 328;
     SiHeapHint                         = 329;
     SiHeapEditHint                     = 330;
     SiStack                            = 331;
     SiStackHint                        = 332;
     SiStackEditHint                    = 333;
     SiDataSegment                      = 334;
     SiSingleShared                     = 335;
     SiSingleSharedHint                 = 336;

     /* Debugger Page */
     SiDebugger                         = 337;
     SiDebuggerHint                     = 338;
     SiDebugInformation                 = 339;
     SiDebugInformationHint             = 340;
     SiIncludeDebugInfo                 = 341;
     SiIncludeDebugInfoHint             = 342;
     SiIncludeLocalSyms                 = 343;
     SiIncludeLocalSymsHint             = 344;
     SiDebuggerOptions                  = 345;
     SiShowWatchHints                   = 346;
     SiShowWatchHintsHint               = 347;
     SiShowAnsiStringCounter            = 348;
     SiShowAnsiStringCounterHint        = 349;
     SiBreakOnExceptions                = 350;
     SiBreakOnExceptionsHint            = 351;
     SiRTLAndSystemExceptions           = 352;
     SiRTLAndSystemExceptionsHint       = 353;
     SiRTLExcptHint                     = 354;
     SiSPCCExceptions                   = 355;
     SiSPCCExceptionsHint               = 356;
     SiSPCCExcptHint                    = 357;

     /* Directories Page */
     SiDirectories                      = 358;
     SiDirectoriesHint                  = 359;
     SiOutputDirectory                  = 360;
     SiOutputDirectoryHint              = 361;
     SiUnitDirectories                  = 362;
     SiUnitDirectoriesHint              = 363;
     SiLibAndSourceDirectories          = 364;
     SiLibAndSourceDirectoriesHint      = 365;
     SiIncludeAndSourceDirs             = 366;
     SiIncludeAndSourceDirsHint         = 367;
     SiComponentDirectories             = 368;
     SiComponentDirectoriesHint         = 369;

     /* ******************************************************************* */
     /* Compiler messages                                                   */
     /* ******************************************************************* */


     SiERR_ILL_CHAR_IN_NUM              = 369+1;
     SiERR_UNDEFINED_IDENT              = 369+2;
     SiERR_DUP_IDENT                    = 369+3;
     SiERR_UNDEF_CONST                  = 369+4;
     SiERR_FILE_OPEN                    = 369+5;
     SiERR_FILE_READ                    = 369+6;
     SiERR_UNEXPECTED_CHAR              = 369+7;
     SiERR_EXPECTED                     = 369+8;
     SiERR_INV_QUALIFIER                = 369+9;
     SiERR_TYPBEZ_EXP                   = 369+10;
     SiERR_RANGE                        = 369+11;
     SiERR_NUMBER_EXP                   = 369+12;
     SiERR_CONST_EXP                    = 369+13;
     SiERR_ILL_FACTOR                   = 369+14;
     SiERR_ILL_POINTER                  = 369+15;
     SiERR_ILL_WITH                     = 369+16;
     SiERR_ILL_STAT                     = 369+17;
     SiERR_UNEXPECTED_END               = 369+18;
     SiERR_TYPE_CONFLICT                = 369+19;
     SiERR_ILL_FOR                      = 369+20;
     SiERR_ILL_CONTINUE                 = 369+21;
     SiERR_ILL_BREAK                    = 369+22;
     SiERR_ILL_SELECTOR                 = 369+23;
     SiERR_SYNTAX                       = 369+24;
     SiERR_ILL_QUALIFIER                = 369+25;
     SiERR_UNDEFINED_FORWARD            = 369+26;
     SiERR_ILL_CONST_ASSIGN             = 369+27;
     SiERR_TOO_MUCH_PARAMS              = 369+28;
     SiERR_TOO_FEW_PARAMS               = 369+29;
     SiERR_ILL_ASSIGNMENT               = 369+30;
     SiERR_DUP_INDEX                    = 369+31;
     SiERR_DUP_SCU                      = 369+32;
     SiERR_FILE_NOT_FOUND               = 369+33;
     SiERR_FILE_WRITE                   = 369+35;
     SiERR_UNIT_GEN                     = 369+36;
     SiERR_CIRC_UNIT                    = 369+37;
     SiERR_UNIT_NOT_FOUND               = 369+38;
     SiERR_UNIT_VERS_MIS                = 369+39;
     SiERR_ILL_EXPCOMP                  = 369+40;
     SiERR_DUP_COMPEXP                  = 369+41;
     SiERR_ILL_KEYWORD_USE              = 369+42;
     SiERR_HEADER_MATCH                 = 369+43;
     SiERR_IDENTIFIER_EXP               = 369+44;
     SiERR_LABEL_NOT_DEF                = 369+45;
     SiERR_DLL_API_EXP                  = 369+46;
     SiERR_ILL_DLLNAME                  = 369+47;
     SiERR_INDEX95                      = 369+48;
     SiERR_NUMCONST_EXP                 = 369+49;
     SiERR_INDEX_NAME_EXP               = 369+50;
     SiERR_STRCONST_EXP                 = 369+51;
     SiERR_ILL_UNIT_NAME                = 369+52;
     SiERR_EXPCOMPUNIT                  = 369+53;
     SiERR_ILL_EXPORT                   = 369+54;
     SiERR_RANGE_CHECK                  = 369+55;
     SiERR_ILL_FORWARD                  = 369+56;
     SiERR_ILLEGAL_STR_DIM              = 369+57;
     SiERR_ILL_SET                      = 369+58;
     SiERR_ILLEGAL_TYPE                 = 369+59;
     SiERR_CLASS_OBJECT_MIX             = 369+60;
     SiERR_TYPENAME_EXP                 = 369+61;
     SiERR_ILL_FUNC_RES                 = 369+62;
     SiERR_DUP_READ                     = 369+63;
     SiERR_DUP_WRITE                    = 369+64;
     SiERR_FIELD_IDENT_EXP              = 369+65;
     SiERR_READ_WRITE_EXP               = 369+66;
     SiERR_ILL_DEFAULT                  = 369+67;
     SiERR_DUP_DEFAULT                  = 369+68;
     SiERR_CANNOT_PUBLISH               = 369+69;
     SiERR_ILL_ABSTRACT                 = 369+70;
     SiERR_ILL_VIR_CONST                = 369+71;
     SiERR_ILL_VIR_DEST                 = 369+72;
     SiERR_ILL_OVERRIDE                 = 369+73;
     SiERR_METHOD_NOT_INPARENT          = 369+74;
     SiERR_DUP_DYN_INDEX                = 369+75;
     SiERR_UNIT_NAME_MIS                = 369+76;
     SiERR_SOURCE_NOT_FOUND             = 369+77;
     SiERR_SOURCE_READ                  = 369+78;
     SiERR_INV_VARREF                   = 369+79;
     SiERR_METHOD_UNDEF                 = 369+80;
     SiERR_FUNC_PROC_EXP                = 369+81;
     SiERR_ILL_METHOD_CALL              = 369+82;
     SiERR_ILL_INHERITED                = 369+83;
     SiERR_INV_MSG_HANDLER              = 369+84;
     SiERR_PROP_WRITEONLY               = 369+85;
     SiERR_PROP_READONLY                = 369+86;
     SiERR_ILL_CLASS_CALL               = 369+87;
     SiERR_PROP_STORED                  = 369+88;
     SiERR_CANNOT_WRITE                 = 369+89;
     SiERR_ILL_RAISE                    = 369+90;
     SiERR_STRING_EXCEEDS_LINE          = 369+91;
     SiERR_IN_ASM                       = 369+92;
     SiERR_CONST_OUT_OF_RANGE           = 369+93;
     SiERR_ILL_ASM                      = 369+94;
     SiERR_ASM                          = 369+95;
     SiERR_FORWARDS_LEFT                = 369+96;
     SiERR_ILL_DIRECTIVE                = 369+97;
     SiERR_CONSTANT_EXP                 = 369+98;
     SiERR_LABEL_EXPECTED               = 369+99;
     SiERR_CANNOT_READ                  = 369+100;
     SiERR_TOO_MUCH_ERR                 = 369+101;
     SiERR_ERRORS                       = 369+102;
     SiERR_SET_CONST                    = 369+103;
     SiERR_INV_FILE_TYPE                = 369+104;
     SiERR_PROP_NOT_EXIST               = 369+105;
     SiERR_EXPERT_COMP                  = 369+106;
     SiERR_COMP_EXPERT                  = 369+107;
     SiERR_DIV_ZERO                     = 369+108;
     SiERR_LOCAL_THREADVAR              = 369+109;
     SiERR_OPERATOR_PARAMS              = 369+110;
     SiERR_OPERATOR_TYPE                = 369+111;
     SiERR_OPERATOR_RESULT              = 369+112;
     SiERR_USER_BREAK                   = 369+113;
     SiERR_INTERNAL                     = 369+114;

     SiWARN_POSS_USE_OF_VAR             = 369+181;
     SiWARN_DECLARED_BUT_NOT_USED       = 369+182;
     SiWARN_PARAMETER_NEVER_USED        = 369+183;
     SiWARN_FUNCTION_SHOULD_RETURN      = 369+184;
     SiWARN_INHERITED_PROP_REDEF        = 369+185;
     SiWARN_INHERITED_VAR_REDEF         = 369+186;
     SiWARN_VIRT_METHOD_REDEF           = 369+187;     


     /* ******************************************************************* */
     /* General Dialog                                                      */
     /* ******************************************************************* */

     /* TEditorSample */
     SiCommentOne                       = 600;
     SiNumber                           = 601;
     SiCommentTwo                       = 602;
     SiCommentThree                     = 603;
     SiCommentFour                      = 604;
     SiThisIsACompilerSwitch            = 606;
     SiExecutionPoint                   = 607;
     SiEnabledBreakPoint                = 608;
     SiErrorLine                        = 609;
     SiInvalidBreakPoint                = 610;

     /* General Settings dialog */
     SiGeneralSettings                  = 611;
     SiSelectApplicationFont            = 612;
     SiProjectDirectory                 = 613;
     SiTemplateDirectory                = 1643;

     /* Editor Page */
     SiEditor                           = 614;
     SiEditorHint                       = 615;
     SiInsertMode                       = 616;
     SiInsertModeHint                   = 617;
     SiAutoIndentMode                   = 618;
     SiAutoIndentModeHint               = 619;
     SiAdditionalIndent                 = 620;
     SiAdditionalIndentHint             = 621;
     SiUnIndent                         = 622;
     SiUnIndentHint                     = 623;
     SiCursorClimbs                     = 624;
     SiCursorClimbsHint                 = 625;
     SiDoubleClickSelLine               = 626;
     SiDoubleClickSelLineHint           = 627;
     SiBlockSelection                   = 628;
     SiBlockSelectionHint               = 629;
     SiBlockSelectionHintDBCS           = 630;
     SiPersistentBlocks                 = 631;
     SiPersistentBlocksHint             = 632;
     SiOverwriteBlocks                  = 633;
     SiOverwriteBlocksHint              = 634;
     SiUndoGroups                       = 635;
     SiUndoGroupsHint                   = 636;
     SiSmartTab                         = 637;
     SiSmartTabHint                     = 638;
     SiHomeToFirstWord                  = 639;
     SiHomeToFirstWordHint              = 640;
     SiAutoBracket                      = 641;
     SiAutoBracketHint                  = 642;
     SiCreateBackups                    = 643;
     SiCreateBackupsHint                = 644;
     SiAppendBAK                        = 645;
     SiAppendBAKHint                    = 646;
     SiSearchTextAtCursor               = 647;
     SiSearchTextAtCursorHint           = 648;
     SiSyntaxHighlight                  = 649;
     SiSyntaxHighlightHint              = 650;
     SiChangeDir                        = 651;
     SiChangeDirHint                    = 652;
     SiFullPathInTitle                  = 653;
     SiFullPathInTitleHint              = 654;
     SiWordWrap                         = 655;
     SiWordWrapHint                     = 656;
     SiColumnForWordWrapping            = 657;
     SiAutoSave                         = 658;
     SiAutoSaveHint                     = 659;
     SiNumberOfModifications            = 660;
     SiTabulatorSize                    = 661;
     SiTabulatorSpaceSize               = 662;
     SiUndoEvents                       = 663;
     SiCountOfUndoableOperations        = 664;
     SiKeyMapping                       = 665;
     SiKeystrokeMapping                 = 666;
     SiCodeEditor                       = 667;
     SiTabSet                           = 668;
     SiTabSetHint                       = 669;
     SiMDI                              = 670;
     SiMDIHint                          = 671;
     SiMouseShape                       = 672;
     SiArrow                            = 673;
     SiArrowHint                        = 674;
     SiIBeam                            = 675;
     SiIBeamHint                        = 676;
     SiCaretShape                       = 677;
     SiUnderline                        = 678;
     SiUnderlineHint                    = 679;
     SiVertical                         = 680;
     SiVerticalHint                     = 681;

     /* Color Page */
     SiColors                           = 682;
     SiColorsHint                       = 683;
     SiElement                          = 684;
     SiColorListHint                    = 685;
     SiColor                            = 686;
     SiColorGridHint                    = 687;
     SiFont                             = 688;
     SiFontComboHint                    = 689;
     SiUseStandardsFor                  = 690;
     SiForeGround                       = 691;
     SiForeGroundHint                   = 692;
     SiBackGround                       = 693;
     SiBackGroundHint                   = 694;
     SiEditorSample                     = 695;
     SiPlainText                        = 696;
     SiReservedWord                     = 697;
     SiString                           = 698;
     SiSymbol                           = 699;
     SiAssembler                        = 700;
     SiMarkedBlock                      = 701;
     SiSearchMatch                      = 702;
     SiValidBreak                       = 703;
     SiInvalidBreak                     = 704;
     SiExecPoint                        = 705;
     SiErrLine                          = 706;
     SiRightMargin                      = 707;
     SiComment1                         = 708;
     SiComment2                         = 709;
     SiComment3                         = 710;
     SiComment4                         = 711;
     SiCompSwitch                       = 712;

     /* Format Page */
     SiFormat                           = 713;
     SiFormatHint                       = 714;
     SiIdentifierStyle                  = 715;
     SiUpperCase                        = 716;
     SiUpperCaseHint                    = 717;
     SiLowerCase                        = 718;
     SiLowerCaseHint                    = 719;
     SiMixed                            = 720;
     SiMixedHint                        = 721;
     SiIndention                        = 722;
     SiBlock                            = 723;
     SiBlockIndentionHint               = 724;
     SiScope                            = 725;
     SiScopeIndention                   = 726;
     SiField                            = 727;
     SiFieldIndention                   = 728;
     SiSpace                            = 729;
     SiSpaceBetweenIdents               = 730;
     SiLineBreak                        = 731;
     SiAfter                            = 732;
     SiCountOfCharsBeforeBreak          = 733;
     SiChars                            = 734;

     /* Designer Page */
     SiDesigner                         = 735;
     SiDesignerHint                     = 736;
     SiGrid                             = 737;
     SiWidth                            = 738;
     SiGridWidthHint                    = 739;
     SiHeight                           = 740;
     SiGridHeightHint                   = 741;
     SiShow                             = 742;
     SiShowHint                         = 743;
     SiActivated                        = 744;
     SiActivatedHint                    = 745;
     SiComponentInsertMode              = 746;
     SiDropAndMove                      = 747;
     SiDropAndMoveHint                  = 748;
     SiDropAndSize                      = 749;
     SiDropAndSizeHint                  = 750;
     SiMultiSelectionMode               = 751;
     SiIncludeRect                      = 752;
     SiIncludeRectHint                  = 753;
     SiTouchRect                        = 754;
     SiTouchRectHint                    = 755;
     SiNewForm                          = 756;
     SiAutoCreation                     = 757;
     SiAutoCreationHint                 = 758;

     /* Browser Page */
     SiBrowser                          = 764;
     SiBrowserHint                      = 765;
     SiBrowsingInfo                     = 766;
     SiConstants                        = 767;
     SiConstantsHint                    = 768;
     SiProcedures                       = 769;
     SiProceduresHint                   = 770;
     SiTypes                            = 771;
     SiTypesHint                        = 772;
     SiVariables                        = 773;
     SiVariablesHint                    = 774;
     SiProperties                       = 775;
     SiPropertiesHint                   = 776;
     SiInherited                        = 777;
     SiInheritedHint                    = 778;
     SiVirtual                          = 779;
     SiVirtualHint                      = 780;
     SiPrivate                          = 781;
     SiPrivateHint                      = 782;
     SiProtected                        = 783;
     SiProtectedHint                    = 784;
     SiPublic                           = 785;
     SiPublicHint                       = 786;
     SiPublished                        = 787;
     SiPublishedHint                    = 788;
     SiBrowsingFiles                    = 789;
     SiRTL                              = 790;
     SiRTLHint                          = 791;
     SiSPCC                             = 792;
     SiSPCCHint                         = 793;
     SiProjectModuleFiles               = 794;
     SiProjectModuleFilesHint           = 795;

     /* General Page */
     SiGeneral                          = 796;
     SiGeneralHint                      = 797;
     SiShowGlobalHints                  = 798;
     SiShowGlobalHintsHint              = 799;
     SiOpenMessageView                  = 800;
     SiOpenMessageViewHint              = 801;
     SiEditorFiles                      = 802;
     SiEditorFilesHint                  = 803;
     SiSCUInfo                          = 804;
     SiSCUInfoHint                      = 805;
     SiProjectSettingsHint              = 806;
     SiEnvironment                      = 807;
     SiEnvironmentHint                  = 808;
     SiApplicationFont                  = 809;
     SiApplicationFontHint              = 810;
     SiActualizeAtSaveAs                = 811;
     SiFormSourceLoc                    = 812;
     SiFormSourceLocHint                = 813;
     SiModuleIdentifier                 = 816;
     SiModuleIdentifierHint             = 817;
     SiUSESStatement                    = 818;
     SiUSESStatementHint                = 819;
     SiSCUResourceName                  = 820;
     SiSCUResourceNameHint              = 821;

     SiStdBrowseHint                    = 824;

     /* Path Page */
     SiPath                             = 1644;
     SiPathHint                         = 1645;
     SiProjectFileNames                 = 814;
     SiProjectFileNamesHint             = 815;
     SiProjectDir                       = 822;
     SiStdDirPrjOpen                    = 823;
     SiTemplateDir                      = 1646;

     /* Compiler Page */
     SiPriority                         = 1647;
     SiPriorityHint                     = 1648;
     SiHelpProgramDirectory             = 1649;


     /* Auto Create Dialog */
     SiMainForm                         = 826;
     SiManualCreate                     = 827;
     SiNoTempSCUInfoFound               = 828;
     SiYouMustSelectAMainForm           = 829;

     /* Project Manager */
     SiProjectManager                   = 830;
     SiAddFileToProject                 = 831;
     SiRemoveFileFromProject            = 832;
     SiAddNewFormToProject              = 833;
     SiDeleteFormFromProject            = 834;
     SiImportFormFiles                  = 835;
     SiFormSettings                     = 836;
     SiInModule                         = 837;
     SiCouldNotAddProjectMainFile       = 838;
     SiCouldNotAddProjectFile           = 839;
     SiCouldNotRemoveFileFromPrj        = 840;
     SiCouldNotRemoveMainFromPrj        = 841;
     SiDeleteFormFromPrjQuery           = 842;
     SiAddMainFile                      = 843;
     SiAddFile                          = 844;
     SiRemoveFile                       = 845;
     SiSetPrimary                       = 846;
     SiClearPrimary                     = 847;
     SiAddForm                          = 848;
     SiRemoveForm                       = 849;
     SiImportForm                       = 850;
     SiSaveFormToFile                   = 851;

     /* Goto line dialog */
     SiGotoLine                         = 852;
     SiNewLineNumber                    = 853;
     SiIsNotAValidLineNumber            = 854;

     /* Run Parameter Dialog */
     SiCommandLineParameters            = 855;
     SiParameter                        = 856;

     /* New Project Dialog */
     SiNewProject                       = 857;
     SiProjectName                      = 858;
     SiTemplate                         = 859;
     SiSelectProjectDirectory           = 860;

     /* Tools Dialog */
     SiTools                            = 861;
     SiProgram                          = 862;
     SiAllFiles                         = 863;
     SiExecutableFiles                  = 864;
     SiExecutableINIFile                = 1361;
     SiBatchFiles                       = 865;
     SiSaveProject                      = 866;
     SiSaveSCU                          = 867;
     SiSaveAllEditors                   = 868;
     SiSaveCurrentEditor                = 869;
     SiCurrentEditor                    = 870;
     SiCurrentEditorLine                = 871;
     SiCurrentEditorColumn              = 872;
     SiPrjName                          = 873;
     SiSCUName                          = 874;
     SiExecutableFile                   = 875;
     SiErrorFileName                    = 876;
     SiErrorLine2                       = 877;
     SiErrorColumn                      = 878;
     SiErrorText                        = 879;
     SiDriveOf                          = 880;
     SiDirectoryOf                      = 881;
     SiFileNameOf                       = 882;
     SiFileNameExtOf                    = 883;

     /* Printer Dialog */
     SiPrinter                          = 884;
     SiPrintRange                       = 885;
     SiPrint                            = 886;
     SiSetup                            = 887;

     /* Language Settings Dialog */
     SiSelectLanguagesToInstall         = 888;
     SiAvailableLanguages               = 889;
     SiLanguagesToInstall               = 890;
     SiErrorWritingMSG                  = 891;
     SiFatalErrorWritingMSG             = 892;
     SiErrorReadingMSG                  = 893;
     SiLanguageAlreadyInstalled         = 894;
     SiOverwriteLanguage                = 895;
     SiSibylResourceFiles               = 896;
     SiFileReadError                    = 897;
     SiIllegalResourceFile              = 898;
     SiResDoesNotContainLanguages       = 899;
     SiNoItemSelected                   = 900;
     SiYouCannotDeleteThisItem          = 901;
     SiLanguageSettings                 = 902;
     SiVDE                              = 903;
     SiVDEHint                          = 904;
     SiInstalledLanguages               = 905;
     SiInstalledLanguagesHint           = 906;
     SiInstalledVDELanguages            = 907;
     SiInstall                          = 908;
     SiInstallHint                      = 909;
     SiDelete                           = 910;
     SiDeleteHint                       = 911;
     SiCurrentLanguage                  = 912;
     SiCurrentLanguageHint              = 913;
     SiCurrentActiveVDELanguage         = 914;
     SiApplication                      = 915;
     SiApplicationHint                  = 916;
     SiChangesHaveBeenMadeToVDE         = 917;
     SiYouMustRestartSibyl              = 918;
     SiRuntimeLanguages                 = 919;
     SiRuntimeLanguagesHint             = 920;
     SiStartupLanguage                  = 921;
     SiStartupLanguageHint              = 922;
     SiSibylLanguageFiles               = 923;
     SiIllegalFileFormat                = 924;
     SiFormNotFound                     = 925;

     SiCloseDlg                         = 955;
     SiCloseDlgHint                     = 956;

     /* Editor */
     SiCursorPosition                   = 1026;

     /* WatchPoint Dialog */
     SiCouldNotSetWatchPoint            = 1027;
     SiWatchPointLimitReached           = 1028;
     SiAdressMustStartOnWord            = 1029;
     SiAdressMustStartOnDoubleWord      = 1030;
     SiIllegalAdressFormat              = 1031;
     SiYouMustSelectAnItem              = 1032;
     SiModifyWatchPoint                 = 1033;
     SiAdressExpression                 = 1034;
     SiBreakOn                          = 1035;
     SiExecute                          = 1036;
     SiWrite                            = 1037;
     SiReadWrite                        = 1038;
     SiBytesToWatch                     = 1039;
     SiOneByte                          = 1040;
     SiTwoBytes                         = 1041;
     SiFourBytes                        = 1042;
     SiCouldNotFreeWatchPoint           = 1043;
     SiBytesAt                          = 1044;
     SiInvalidWatchPoint                = 1045;
     SiWatchExecute                     = 1046;
     SiWatchReadWrite                   = 1047;
     SiWatchWrite                       = 1048;
     SiWatchPoints                      = 1049;
     SiNewWatchPoint                    = 1050;
     SiNewWatchPointHint                = 1051;
     SiModifyWatchPnt                   = 1052;
     SiModifyWatchPntHint               = 1053;
     SiDebuggerNotRunning               = 1054;
     SiAvailableWatchPoints             = 1055;

     /* Inspect Dialog */
     SiInspecting                       = 1057;
     SiInspectExpression                = 1058;

     /* Add watch dialog */
     SiAddWatch                         = 1059;
     SiRemoveAllWatches                 = 1060;
     SiWatchPopupAddWatch               = 1061;
     SiWatchPopupRemoveWatch            = 1062;
     SiWatchPopupRemoveAllWatches       = 1063;
     SiWatchPopupInspectValue           = 1064;
     SiWatchPopupChangeValue            = 1065;
     SiWatchPopupItemEnabled            = 1066;
     SiWatchWindow                      = 1067;
     SiExpression                       = 1068;
     SiValue                            = 1069;
     SiErrorInExpression                = 1070;

     /* Evaluate/Modify Dialog */
     SiEvaluateModify                   = 1071;
     SiNewValue                         = 1072;
     SiEvaluate                         = 1073;
     SiModify                           = 1074;
     SiDone                             = 1075;

     /* View BreakPoints Dialog */
     SiViewBreakPoints                  = 1076;
     SiAtLinearAdress                   = 1077;

     /* Local Variables Window */
     SiLocalVariables                   = 1078;
     SiVariable                         = 1079;

     /* Symbols Window */
     SiPublicSymbols                    = 1080;

     /* Debugger messages */
     SiProgramTerminatedWithRC          = 1081;
     SiCouldNotLoadProcess              = 1082;
     SiSpecifySourceFile                = 1083;
     SiPascalFiles                      = 1084;
     SiSourceFileNotFound               = 1085;
     SiSpecifyAnotherFile               = 1086;
     SiModuleContainNoSourceFile        = 1087;
     SiChangeSourceFile                 = 1088;
     SiSelectASourceModule              = 1089;
     SiSrcFileNotFound                  = 1090;
     SiNoSourceFileInfoAvail            = 1091;
     SiSelectAnItemOrPressCancel        = 1092;
     SiNoProcessLoaded                  = 1093;
     SiIllAdressFormat                  = 1094;
     SiStorageCaption                   = 1095;
     SiGotoAdress                       = 1096;
     SiEnterAdress                      = 1097;
     SiEnterNewDataBytes                = 1098;
     SiIllegalNumericFormat             = 1099;
     SiIllegalValueForUpdate            = 1100;

     /* Dump Window */
     SiDumpPopupGoto                    = 1101;
     SiDumpPopupChange                  = 1102;
     SiDumpPopupDisplayAs               = 1103;

     /* CPU Window */
     SiCPUWindow                        = 1104;
     SiCPUPopupGoto                     = 1105;
     SiCPUPopupOrigin                   = 1106;
     SiCPUPopupStepInto                 = 1107;
     SiCPUPopupStepOver                 = 1108;
     SiNotUsed                          = 1109;
     SiDumpPage                         = 1110;
     SiDumpHint                         = 1111;
     SiStackPage                        = 1112;
     SiStackPageHint                    = 1113;
     SiCouldNotGetRegisters             = 1114;

     /* Object Inspector */
     SiObjectInspector                  = 1115;
     SiIProperties                      = 1116;
     SiIEvents                          = 1117;
     SiDupMethodName                    = 1118;
     SiIllegalMethod                    = 1119;
     SiPropertyIsReadOnly               = 1120;
     SiNoPropertyEditor                 = 1121;
     SiUnitNotFound                     = 1122;

     /* Edit Repository Object Dialog */
     SiEditRepositoryObject             = 1123;
     SiTitle                            = 1124;
     SiDescription                      = 1125;
     SiAuthor                           = 1126;
     SiSelectABitmap                    = 1127;
     SiBitmapFiles                      = 1128;
     SiInvalidBitmapFile                = 1129;
     SiBitmapMustBe32x32                = 1130;
     SiSelectABMP                       = 1131;
     SiBitmapFilesPCX                   = 1359;
     SiBitmapFilesGIF                   = 1360;

     /* Repository Dialog */
     SiRepository                       = 1132;
     SiAddPage                          = 1133;
     SiEnterPageName                    = 1134;
     SiIllegalPageName                  = 1135;
     SiPageAlreadyUsed                  = 1136;
     SiRenamePage                       = 1137;
     SiEraseRepositoryForm              = 1138;
     SiPages                            = 1139;

     SiObjects                          = 1140;
     SiRepMainForm                      = 1141;
     SiRepMainFormHint                  = 1142;
     SiRepNewForm                       = 1143;
     SiRepNewFormHint                   = 1144;
     SiRepNewProject                    = 1145;
     SiRepNewProjectHint                = 1146;
     SiRepAddPage                       = 1147;
     SiRepAddPageHint                   = 1148;
     SiRepDeletePage                    = 1149;
     SiRepDeletePageHint                = 1150;
     SiRepRenamePage                    = 1151;
     SiRepRenamePageHint                = 1152;
     SiRepEditObject                    = 1153;
     SiRepEditObjectHint                = 1154;
     SiRepDeleteObject                  = 1155;
     SiRepDeleteObjectHint              = 1156;
     SiDragItems                        = 1157;
     SiFileWriteError                   = 1158;
     SiFileCreateError                  = 1159;
     SiForm                             = 1160;
     SiUnit                             = 1161;
     SiWDSibylHelp                      = 1640;
     SiResource                         = 1641;
     SiText                             = 1162;
     SiComponent                        = 1163;
     SiCompLib                          = 1164;
     SiExceptInExpert                   = 1165;
     SiFileCreated                      = 1638;

     /* Repository Pages */
     SiNewPage                          = 1166;
     SiFormsPage                        = 1167;
     SiProjectsPage                     = 1168;

     /* Save Form as Repository Template */
     SiSaveFormAsRepositoryTemp         = 1169;
     SiForms                            = 1170;
     SiPage                             = 1171;
     SiYouMustSpecifyAForm              = 1172;
     SiYouMustSpecifyATitle             = 1173;
     SiYouMustSpecifyARepPage           = 1174;
     SiErrorGenSCU                      = 1175;
     SiNoSCUInfoForForm                 = 1176;
     SiTitleOfObjAlreadyUsed            = 1177;
     SiSIBYLFRMCorrupt                  = 1178;
     SiErrorWritingBitmap               = 1179;
     SiSaveFormTemplatesToFile          = 1180;
     SiSibylFormTemplates               = 1181;
     SiYouMustSpecifyAFileName          = 1182;
     SiAreYouSureToReplace              = 1183;

     /* Export Template Form(s) Dialog */
     SiExportTemplateForms              = 1184;
     SiAvailableTemplates               = 1185;
     SiTargetTemplates                  = 1186;
     SiTargetFile                       = 1187;

     /* Import Form Templates Dialog */
     SiLoadFormTemplatesFromFile        = 1188;
     SiImportTemplateForms              = 1189;
     SiTemplatesToImport                = 1190;
     SiFileContainsNoFormTemplates      = 1191;

     /* Sibyl MAIN */
     SiMenuStopMacroRecording           = 1192;
     SiMenuRestore                      = 1193;
     SiMenuMax                          = 1194;
     SiDebuggerRunning                  = 1195;
     SiProcessTerminated                = 1196;
     SiProcessLoaded                    = 1197;
     SiErrorLoadingProcess              = 1198;
     SiNoTargetWindow                   = 1199;
     SiCannotOpenCPUWindow              = 1200;
     SiWatchPointHit                    = 1201;
     SiNoCodeGeneratedForThisLine       = 1202;
     SiCouldNotSetBreakPoint            = 1203;
     SiExceptionOccured                 = 1204;
     SiIgnoreWillRunHandlers            = 1205;
     SiAbortTerminates                  = 1206;
     SiRetryWillStop                    = 1207;
     SiDebuggerError                    = 1208;
     SiHelpWindowTitle                  = 1209;

     /* Bitmap and Icon Property Editor */
     SiLoad                             = 1210;
     SiLoadHint                         = 1211;
     SiClear                            = 1212;
     SiClearHint                        = 1213;
     SiInvalidBitmap                    = 1214;
     SiSelectAnIcon                     = 1215;
     SiIconFiles                        = 1216;
     SiInvalidIcon                      = 1217;

     /* Strings Property Editor */
     SiEditStrings                      = 1218;
     SiClickHereToLoadFromFile          = 1219;
     SiInvalidOutlineHierarchy          = 1220;

     /* Master/Detail database field Editor */
     SiMasterDetailDBFieldEditor        = 1221;
     SiPrimaryKeys                      = 1222;
     SiTableQueryItems                  = 1223;
     SiAddHint                          = 1224;
     SiDelHint                          = 1225;
     SiMasterSourceMustBeDataSource     = 1226;

     /* DB Grid Columns Property Editor */
     SiDBGridColumnsEditor              = 1227;
     SiUntitled                         = 1228;
     SiColumns                          = 1229;
     SiNewButton                        = 1230;
     SiAddAllFields                     = 1231;
     SiDeleteAllColumns                 = 1232;
     SiColumnProperties                 = 1233;
     SiAlignment                        = 1234;
     SiPenColor                         = 1235;
     SiFieldName                        = 1236;
     SiReadOnly                         = 1237;
     SiRestoreDefaults                  = 1238;
     SiTitleProperties                  = 1239;
     SiCaption                          = 1240;

     /* StatusBar Panels Editor */
     SiStatusbarPanelsEditor            = 1241;
     SiPanels                           = 1242;
     SiNewPanel                         = 1243;
     SiDeletePanel                      = 1244;
     SiPanelProperties                  = 1245;
     SiTextLabel                        = 1246;
     SiWidthLabel                       = 1247;
     SiStyleLabel                       = 1248;
     SiBevelLabel                       = 1249;
     SiUpdate                           = 1250;
     SiUpdateHint                       = 1251;

     /* HeaderControl Sections Property Editor */
     SiHeaderControlSectionsEditor      = 1252;
     SiSections                         = 1253;
     SiNewSection                       = 1254;
     SiDeleteSection                    = 1255;
     SiSectionProperties                = 1256;
     SiMinMaxLabel                      = 1257;
     SiUpdateSection                    = 1258;
     SiAllowClick                       = 1259;
     SiAllowSize                        = 1260;

     /* Notebookpage Property Editor */
     SiPageEditor                       = 1261;
     SiEditSelectedPage                 = 1262;
     SiInsertNewPage                    = 1263;
     SiDeleteSelectedPage               = 1264;
     SiTheControlMustContainPage        = 1265;
     SiDeletePageConfirm                = 1266;
     SiSetupPage                        = 1267;
     SiPageHint                         = 1268;
     SiHelpContext                      = 1269;

     /* Configure Palette Page dialog */
     SiRenamePalettePage                = 1270;
     SiEnterNewPageName                 = 1271;
     SiRename                           = 1272;
     SiPageAlreadyExists                = 1273;
     SiNewPalettePage                   = 1274;
     SiInvalidPageName                  = 1275;
     SiRemovePage                       = 1276;
     SiConfigureComponentPalette        = 1277;
     SiAvailablePages                   = 1278;
     SiAvailableComponents              = 1279;
     SiNavigatorCompNotFound            = 1280;
     SiUsesRegisterClasses              = 1281;
     SiAnExceptLoadingBitmap            = 1282;
     SiComponentDisabled                = 1283;
     SiSelectMode                       = 1284;
     SiScrollComponentsBack             = 1285;
     SiScrollComponentsForward          = 1286;

     /* Component List */
     SiComponentList                    = 1287;
     SiSelectByName                     = 1288;
     SiAddToForm                        = 1289;
     SiAddToFormHint                    = 1290;

     /* Compiler */
     SiInternalCompError                = 1300;
     SiProgramAlreadyRunning            = 1301;
     SiCompilerAlreadyRunning           = 1302;
     SiSuccess                          = 1303;
     SiFileIsCorrupt                    = 1304;
     SiNoDependencyInfo                 = 1305;
     SiProjectModified                  = 1306;
     SiSCUModified                      = 1307;
     SiFileNotYetCompiled               = 1308;
     SiSPUInvalid                       = 1309;
     SiSCUInvalid                       = 1310;
     SiDependenciesOk                   = 1311;

     /* Sibyl editor */
     SiWarningAt                        = 1312;
     SiErrorAt                          = 1313;
     SiFatalErrorAt                     = 1314;
     SiNoPrimaryFileFound               = 1315;
     SiCouldNotAddToProject             = 1316;
     SiSibylForOS2                      = 1317;
     SiSibylForWin32                    = 1318;
     SiEdPopupClose                     = 1319;
     SiEdPopupOpen                      = 1320;
     SiEdPopupTopicSearch               = 1321;
     SiEdPopupCompile                   = 1322;
     SiEdPopupMake                      = 1323;
     SiEdPopupToggleBreak               = 1324;
     SiEdPopupRunToCursor               = 1325;
     SiEdPopupEvalModify                = 1326;
     SiEdPopupAddWatch                  = 1327;
     SiEdPopupReadOnly                  = 1328;
     SiEdPopupMessageWindow             = 1329;
     SiEdPopupProperties                = 1330;
     SiEdPopupOpenFile                  = 1331;
     SiEdPopupReOpenFile                = 1357;
     SiEdPopupCompileFile               = 1332;
     SiEdPopupMakeFile                  = 1333;
     SiAllEditors                       = 1334;
     SiCannotRenameFileUsed             = 1335;
     SiInsertPrivateDeclsHere           = 1337;
     SiInsertPublicDeclsHere            = 1338;
     SiClassDefNotFound                 = 1339;
     SiDupMethWithDiffParams            = 1340;
     SiAppCreateFormNotFound            = 1341;
     SiCouldNotChangeMainForm           = 1342;
     SiProjectPrimNotFound              = 1343;
     SiDuplicateClassIdent              = 1344;
     SiDuplicateComponentIdent          = 1345;
     SiDuplicateMethodIdent             = 1346;
     SiInputMode                        = 1347;
     SiReadOnlyState                    = 1348;
     SiModifiedState                    = 1349;
     SiInfo                             = 1350;
     SiProgramReset                     = 1351;
     SiFullSpeed                        = 1352;
     SiDockingToolBar                   = 1353;
     SiFileModifiedReOpen               = 1358;

     /* Printer dialog */
     SiLayout                           = 1354;
     SiSyntaxBold                       = 1355;
     SiCommentsItalic                   = 1356;

     /* Browser */
     SiBrowseObjects                    = 1400;
     SiBrowseUnits                      = 1401;
     SiBrowseGlobals                    = 1402;
     SiIllegalUnitFormat                = 1403;
     SiNoBrowseInfoAvail                = 1404;
     SiCloseBrowser                     = 1405;
     SiBrObjects                        = 1406;
     SiBrUnits                          = 1407;
     SiBrGlobals                        = 1408;
     SiBrViewSource                     = 1409;
     SiBrUpdate                         = 1410;
     SiBrProperties                     = 1411;

     /* Form generation */
     SiCannotInsertClassDef             = 1412;
     SiNotAValidIdent                   = 1413;
     SiDupGlobalIdent                   = 1414;
     SiDupIdent                         = 1415;
     SiCouldNotRenameForm               = 1416;
     SiDeleteHandlerQuery               = 1417;

     /* Form Import */
     SiImportSibylDelphiForm            = 1450;
     SiIllegalIntegerValue              = 1451;
     SiIllegalIdentValue                = 1452;
     SiValueCheckFailed                 = 1453;
     SiIllegalChar                      = 1454;
     SiIllegalString                    = 1455;
     SiIllegalSet                       = 1456;
     SiIllegalCollection                = 1457;
     SiIllegalValueType                 = 1458;
     SiIllegalIntegerSize               = 1459;
     SiIllegalPropertyType              = 1460;
     SiIllegalIdent                     = 1461;
     SiIllegalBoolean                   = 1462;
     SiCompClassNotFound                = 1463;
     SiConvertError                     = 1464;
     SiCouldNotFindRelUnit              = 1465;
     SiSelectAFormToImport              = 1466;
     SiLoadError                        = 1467;
     SiAllFormFiles                     = 1468;
     SiSibylFormFiles                   = 1469;
     SiDelphiFormFiles                  = 1470;

     /* Component Management */
     SiPaletteStandard                  = 1472;
     SiPaletteAdditional                = 1473;
     SiPaletteExtra                     = 1474;
     SiPaletteDatabase                  = 1475;
     SiPaletteMultimedia                = 1476;
     SiPaletteDialog                    = 1477;
     SiPaletteSystem                    = 1478;
     SiPaletteSamples                   = 1479;
     SiPaletteUser                      = 1480;
     SiUnableToCreateExpertsMenu        = 1481;
     SiExperts                          = 1482;
     SiActivateExperts                  = 1483;
     SiTooManyExperts                   = 1484;
     SiSelectComponentsToInstall        = 1485;
     SiComponentsToInstall              = 1486;
     SiSelectCompOrExpert               = 1487;
     SiCompAlreadyInstalled             = 1488;
     SiInstallComponentUnit             = 1489;
     SiSibylCompFiles                   = 1490;
     SiErrorOpenCompUnit                = 1491;
     SiErrorReadingCompUnit             = 1492;
     SiExpert                           = 1493;
     SiUnitDoesNotContainComps          = 1494;
     SiCouldNotLoadCompLib              = 1495;
     SiCouldNotInitCompLib              = 1496;
     SiCouldNotFreeCompLib              = 1497;
     SiLoadLibrary                      = 1498;
     SiDynamicLinkLibraries             = 1499;
     SiCannotLoadCompLib                = 1500;
     SiYouMustSelectADLL                = 1501;
     SiClosePrjToLoadCompLib            = 1502;
     SiClosePrjToCompileCompLib         = 1503;
     SiSelectComp                       = 1504;
     SiRemoveExpertUnitQuery            = 1505;
     SiRemoveComponents                 = 1506;
     SiInstalledUnits                   = 1507;
     SiInstalledComps                   = 1508;
     SiRemoveSelectedComps              = 1509;
     SiCannotUpdatePalette              = 1510;
     SiSpecifyCompName                  = 1511;
     SiSpecifyAncestorClass             = 1512;
     SiIsNotRegistered                  = 1513;
     SiSpecifyUnitName                  = 1514;
     SiDupCompUnitName                  = 1515;
     SiGenNewComp                       = 1516;
     SiComponentName                    = 1517;
     SiAncestorClass                    = 1518;
     SiUnitName                         = 1519;
     SiDeclareNewClass                  = 1520;
     SiDefineCompsToExport              = 1521;
     SiDefineNavPage                    = 1522;
     SiRegisterClasses                  = 1523;
     SiPaletteInternet                  = 1524;

     /* Browser */
     SiBrowserConstants                 = 1600;
     SiBrowserProcedures                = 1601;
     SiBrowserTypes                     = 1602;
     SiBrowserVariables                 = 1603;
     SiBrowserProperties                = 1604;
     SiBrowserInherited                 = 1605;
     SiBrowserVirtual                   = 1606;
     SiBrowserPrivate                   = 1607;
     SiBrowserProtected                 = 1608;
     SiBrowserPublic                    = 1609;
     SiBrowserPublished                 = 1610;

     /* Project Management */
     SiIncludeFiles                     = 1611;
     SiResourceFiles                    = 1612;
     SiWDSibylHelpFiles                 = 1639;
     SiComplibSources                   = 1613;
     SiAssemblerFiles                   = 1614;
     SiOpen                             = 1615;
     SiLoadingEnv                       = 1616;
     SiSavingEnv                        = 1617;
     SiCouldNotCreateTempSCU            = 1618;
     SiCannotRun                        = 1619;
     SiCouldNotCreateSCUForForm         = 1620;
     SiFileAlreadyExistsOverwrite       = 1621;
     SiSavingSCUInfo                    = 1622;
     SiCouldNotCreateSCUFile            = 1623;
     SiLoadingPrj                       = 1624;
     SiLoadingSCUInfo                   = 1625;
     SiCouldNotOpenSCUFile              = 1626;
     SiCouldNotReadSCUFile              = 1627;
     SiIllegalSCUFormat                 = 1628;
     SiSavingPrj                        = 1629;
     SiCouldNotCreatePrjFile            = 1630;
     SiSaveCurrentPrj                   = 1631;
     SiSaveProjectAs                    = 1632;
     SiSibylProjectFiles                = 1633;
     SiPrjAlreadyExistsOverwrite        = 1634;
     SiOpenProject                      = 1635;
     SiPrjDoesNotExist                  = 1636;
     SiLoadingForm                      = 1637;

     /* MainMenu */
     SiMenuToolbars                     = 2000;
     SiMenuToolbarsHint                 = 2001;
     SiToolbarsCaption                  = 2002;

     SiCompilerRunning                  = 2003;
     Si3DButtons                        = 2004;
     SiEdPopupSave                      = 2005;

     /* Forms Page */
     SiPrjForms                         = 2006;
     SiFormsHint                        = 2007;
     SiMainFormHint                     = 2008;
     SiAutoCreateFormsHint              = 2009;


     /* Alignemnt Palette */
     SiAlign1                           = 2011;
     SiAlign2                           = 2012;
     SiAlign3                           = 2013;
     SiAlign4                           = 2014;
     SiAlign5                           = 2015;
     SiAlign6                           = 2016;
     SiAlign7                           = 2017;
     SiAlign8                           = 2018;
     SiAlign9                           = 2019;
     SiAlign10                          = 2020;
     SiAlign11                          = 2021;
     SiAlign12                          = 2022;
     SiAlign13                          = 2023;
     SiAlign14                          = 2024;
     SiForceAlign                       = 2025;
     SiRefresh                          = 2026;
     SiDeleteCtrl                       = 2027;
     SiGridVisible                      = 2028;
     SiSnapToGrid                       = 2029;
     SiFocusLastForm                    = 2030;

     /* Formdesigner Popup */
     SiFormPopupCopy                    = 2031;
     SiFormPopupPaste                   = 2032;
     SiFormPopupDelete                  = 2033;
     SiFormPopupAlignment               = 2034;
     SiFormPopupLayoutPalette           = 2035;
     SiFormPopupObjectInspector         = 2036;
     SiFormPopupFormSourceLocation      = 2037;
     SiFormPopupSaveFormToFile          = 2038;
     SiFormPopupSaveFormAsTemplate      = 2039;
     SiFormPopupProperties              = 2040;


     /* Change Form Location Dialog */
     SiChangeFormLocation               = 2041;
     SiChange                           = 2042;

     /* Save Form to File Dialog */
     SiSaveFormToFileCaption            = 2043;
     SiCouldNotWriteFile                = 2044;

     /* Test Insert Component */
     SiNoTComponentDescendant           = 2045;

     /* Clipboard Operationen */
     SiCannotOpenClipboard              = 2046;
     SiCannotAllocateSharedMem          = 2047;

     /* Delete Components */
     SiErrorDestroyingComponent         = 2048;

     SiAddMainFileToProject             = 2049;
     SiMenuSetPrimary                   = 2050;
     SiMenuSetPrimaryHint               = 2051;

     /* Project Settings Dialog */
     SiAuto                             = 2052;
     SiAutoHint                         = 2053;
     Si3DButtonsHint                    = 2054;
     SiBitmapGlyph                      = 2055;
     SiBitmapGlyphHint                  = 2056;
     SiDroppingFile                     = 2057;
     SiDropOpen                         = 2058;
     SiDropOpenHint                     = 2059;
     SiDropImport                       = 2060;
     SiDropImportHint                   = 2061;

     SiNew                              = 2062;
     SiAddFileOkName                    = 2063;
     SiTool                             = 2064;
     SiYouCannotDeleteThisLanguage      = 2065;
     SiYouCannotDisableActiveLang       = 2066;


     /* Control Centre */
     SiBuild                            = 2067;
     SiDebug                            = 2068;
     SiLocals                           = 2069;
     SiWatch                            = 2070;
     SiCallStack                        = 2071;
     SiBreakpoints                      = 2072;
     SiStorage                          = 2073;

     SiCompilerStartOS2                 = 2271;
     SiCompilerStartWin32               = 2272;
     SiCompilerEnd                      = 2273;

     /* New Dialog */
     SiNewThreadObject                  = 2074;
     SiClassName                        = 2075;
     SiPlaceThreadCodeHere              = 2076;
     SiNewComponentLibrary              = 2077;
     SiCompLibName                      = 2078;


     /* Docking Toolbars */
     SiToolbarFile                      = 2079;
     SiToolbarEdit                      = 2080;
     SiToolbarSearch                    = 2081;
     SiToolbarView                      = 2082;
     SiToolbarComponents                = 2083;
     SiToolbarDebug                     = 2084;
     SiToolbarProject                   = 2085;
     SiToolbarOptions                   = 2086;
     SiToolbarWindow                    = 2087;
     SiToolbarHelp                      = 2088;
     SiToolbarLayout                    = 2089;
     SiToolbarControlCentre             = 2090;

     /* Strings Property Editor */
     SiFileNotFound                     = 2091;

     /* Filter Property Editor */
     SiEditFilter                       = 2092;
     SiFilterName                       = 2093;
     SiFilterMask                       = 2094;

     /* Forms Page */
     SiAutoCreate                       = 2095;

     /* General Page */
     SiEditorIconbar                    = 2096;
     SiEditorIconbarHint                = 2097;
     SiLoadLastPrj                      = 2098;
     SiLoadLastPrjHint                  = 2099;
     SiAskRecompile                     = 2100;
     SiAskRecompileHint                 = 2101;

     SiFilesOutOfDate                   = 2102;
     SiRebuildFiles                     = 2103;

     /* DB Colum Property Editor */
     SiColumnPropertiesHint             = 2104;
     SiTitlePropertiesHint              = 2105;
     SiColumnWidth                      = 2106;


     /* Window List */
     SiWindowList                       = 2107;
     SiWindowShow                       = 2108;
     SiWindowClose                      = 2109;

     /* MacroList */
     SiEditorMacroList                  = 2110;
     SiEditorMacroPlay                  = 2111;
     SiEditorMacroDelete                = 2112;
     SiMacroName                        = 2113;
     SiEnterNewMacroName                = 2114;

     /* Clipboard History */
     SiClipboardHistory                 = 2115;
     SiClipboardPaste                   = 2116;
     SiClipboardDelete                  = 2117;

     /* DFM Convert */
     SiIncompatibleIconBitmapFormat     = 2118;

     /* Color Property */
     SiMore                             = 2119;

     /* Customize Dialog */
     SiMenuCustomize                    = 2120;
     SiMenuCustomizeHint                = 2121;
     SiCustomizeSettings                = 2122;
     SiSpeedbar                         = 2123;
     SiSpeedbarHint                     = 2124;
     SiMenuListHint                     = 2125;
     SiAvailableSpeedItems              = 2126;
     SiDragnDropSpeedButtons            = 2127;

     /* Repository Dialog */
     SiConfigureRepository              = 2128;

     /* Inspector */
     SiPropertyNone                     = 2129;

     /* DBGrid Columns Property Editor */
     SiDBGridFont                       = 2130;


     /* Image List Property Editor */
     SiEditImageList                    = 2200;
     SiAddBitmap                        = 2201;
     SiAddMask                          = 2202;
     SiRemoveImage                      = 2203;
     SiReplaceBitmap                    = 2204;
     SiReplaceMask                      = 2205;
     SiSaveBitmap                       = 2206;
     SiSaveMask                         = 2207;
     SiInsertImage                      = 2208;
     SiAddImage                         = 2209;
     SiCurrentImage                     = 2210;
     SiImageCount                       = 2211;
     SiNextImage                        = 2212;
     SiPreviousImage                    = 2213;
     SiAutoCreateMask                   = 2214;
     SiAutoSizeImage                    = 2215;
     SiStatus                           = 2216;

     /* Print File Dialog */
     SiPrintFile                        = 2217;
     SiPrintAll                         = 2218;
     SiPrintSelected                    = 2219;

     /* Linker Page */
     SiExePacking                       = 2220;
     SiExePackNone                      = 2221;
     SiExePackNoneHint                  = 2222;
     SiExePack1                         = 2223;
     SiExePack1Hint                     = 2224;
     SiExePack2                         = 2225;
     SiExePack2Hint                     = 2226;
     SiVDM                              = 2227;
     SiRunFromVDM                       = 2228;
     SiRunFromVDMHint                   = 2229;

     /* Find in Files Dialog */
     SiFindFiles                        = 2230;
     SiFindInFiles                      = 2231;
     SiFindInFilesHint                  = 2232;
     SiFilter                           = 2233;
     SiDirectory                        = 2234;
     SiSubDirectories                   = 2235;
     SiSearchingFor                     = 2236;
     SiMatchesFound                     = 2237;
     SiSelectDirectory                  = 2238;

     SiMenuMatchingBrace                = 2239;
     SiMenuMatchingBraceHint            = 2240;

     SiTbPopupProperties                = 2241;

     SiAssertions                       = 2242;
     SiAssertionsHint                   = 2243;
     SiSaveConstructors                 = 2244;
     SiSaveConstructorsHint             = 2245;

     /* General Page */
     SiSound                            = 2246;
     SiSoundHint                        = 2247;
     /* Bitmap Property Editor */
     SiEmpty                            = 2248;

     /* Load CompLib */
     SiTryRecompileComplib              = 2249;

     /* Code Insight Page */
     SiCodeInsight                      = 2250;
     SiAutomaticFeatures                = 2251;
     SiCodeCompletion                   = 2252;
     SiCodeParameters                   = 2253;
     SiTooltipExprEvaluation            = 2254;
     SiDelaySec                         = 2255;
     SiCodeTemplates                    = 2256;
     SiTemplates                        = 2257;
     SiTemplateName                     = 2258;
     SiTemplateDescription              = 2259;
     SiTemplateCode                     = 2260;
     SiTemplateAdd                      = 2261;
     SiTemplateEdit                     = 2262;
     SiTemplateDelete                   = 2263;
     SiAddCodeTemplate                  = 2264;
     SiEditCodeTemplate                 = 2265;
     SiCodeInsightHint                  = 2266;

     /* Application Icon Page */
     SiCannotDisplayAppIcon             = 2267;
     SiIconFileMaybeInvalid             = 2268;
     SiInvalidAppIcon                   = 2269;
     SiIgnoringAppIcon                  = 2270;

     /* Language-Names */
     SiLang_German                      = 4000;
     SiLang_English                     = 4001;
     SiLang_Dutch                       = 4002;
     SiLang_Italian                     = 4003;
     SiLang_Russian                     = 4004;

     /* ******************************************************************* */
     /* Note: Indizes above 65000 are reserved by SPCC !! */

/* -- date -- -- from -- -- changes ---------------------------------------------- */
/*  01-Aug-03  WD         Menue: CreateLngFile eingebaut */
/*  03-Aug-03  WD         Entfernen des TipOfTheDay-Dialog */
/*  15-Nov-04  WD         Texte: SiCompilerStartOS2, SiCompilerStartWin32, */
/*                        SiCompilerEnd eingebaut */
/*  11-Mar-05  WD         WDSibyl-Hilfe-Dateien eingebaut (1639, 1640)  */
/*  25-Mar-05  WD         Resource-Datei eingebaut (1641) */
/*  05-Apr-05  WD         Definieren des Namens der Help-Datei (1642) */
/*                        General-Setting: Path-Page (1643-1646) */
/*  14-Mai-05  WD         General-Setting: Compiler-Page(1647-1649 u. 4000-4001) */
/*  23-Dez-05  WD         Sprache: Niederl„ndisch */
/*  12-Mai-06  WD         Sprache: Russisch */
/*  19-Jun-06  WD         Popup-Menue: ReOpenFile (1357, 1358) eingebaut. */
/*  15-Jan-07  WD         Bild-Formate (SiBitmapFilesPCX, 1359) und SiBitmapFilesGIF (1360) eingebaut. */
/*  25-Dec-07  WD         ExecutableINIFile (SiExecutableINIFile, 1361 */


